const KEY='retroplaybr_games_v2';
const starter=[
 {name:'God of War: Chains of Olympus',platform:'PSP',cover:'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800',link:'https://terabox.com/'},
 {name:'Pokémon Fire Red',platform:'GBA',cover:'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=800',link:'https://terabox.com/'},
 {name:'Super Mario 64',platform:'N64',cover:'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800',link:'https://terabox.com/'},
 {name:'Mario Kart DS',platform:'DS',cover:'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=800',link:'https://terabox.com/'}
];
let games=JSON.parse(localStorage.getItem(KEY)||'null')||starter, filter='Todos';
const $=id=>document.getElementById(id); const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(games));render()}
function render(){const q=$('search').value.toLowerCase();$('filters').innerHTML=['Todos','PSP','GBA','N64','DS'].map(p=>`<button class="${filter===p?'active':''}" data-filter="${p}">${p}</button>`).join('');$('catalog').innerHTML=games.filter(g=>(filter==='Todos'||g.platform===filter)&&g.name.toLowerCase().includes(q)).map(g=>`<article class="card"><img src="${esc(g.cover)}" alt="Capa de ${esc(g.name)}" onerror="this.style.opacity='.25'"><div class="card-body"><h3>${esc(g.name)}</h3><span class="tag">${esc(g.platform)}</span><br><a href="${esc(g.link)}" target="_blank" rel="noopener"><button>Baixar no Terabox</button></a></div></article>`).join('')||'<div class="empty">Nenhum jogo encontrado.</div>';if(!$('dashboard').classList.contains('hidden'))$('adminList').innerHTML=games.map((g,i)=>`<div class="admin-item"><span>${esc(g.name)} · ${esc(g.platform)}</span><button data-remove="${i}">Excluir</button></div>`).join('')}
$('search').oninput=render;$('filters').onclick=e=>{if(e.target.dataset.filter){filter=e.target.dataset.filter;render()}};$('adminBtn').onclick=()=>{$('modal').classList.remove('hidden');$('login').classList.remove('hidden');$('dashboard').classList.add('hidden');$('password').focus()};$('close').onclick=()=> $('modal').classList.add('hidden');$('loginBtn').onclick=()=>{if($('password').value==='abcd'){$('login').classList.add('hidden');$('dashboard').classList.remove('hidden');render()}else $('error').textContent='Senha incorreta.'};$('gameForm').onsubmit=e=>{e.preventDefault();games.push({name:$('name').value.trim(),platform:$('platform').value,cover:$('cover').value,link:$('link').value});save();e.target.reset()};$('adminList').onclick=e=>{if(e.target.dataset.remove!=null){games.splice(Number(e.target.dataset.remove),1);save()}};$('logout').onclick=()=>{$('modal').classList.add('hidden');$('password').value=''};render();
